from tkinter import *
import tkinter as tk


window = Tk() 
window.geometry("300x500")
window.title("SPL Calculator")

Label(window, text="Vas: ").pack()
entry = Entry(window)
entry.pack()
Label(window, text="fs: ").pack()
entry = Entry(window)
entry.pack()
Label(window, text="Qts: ").pack()
entry = Entry(window)
entry.pack()
Label(window, text="Qes: ").pack()
entry = Entry(window)
entry.pack()
Label(window, text="Qms: ").pack()
entry = Entry(window)
entry.pack()
Label(window, text="Xmax: ").pack()
entry = Entry(window)
entry.pack()
Label(window, text="Sd: ").pack()
entry = Entry(window)
entry.pack()
Label(window, text="Sensitivity: ").pack()
entry = Entry(window)
entry.pack()
Label(window, text="Re: ").pack()
entry = Entry(window)
entry.pack()

Button(window, text="ON").pack()
#turn_on.pack()

window.mainloop()
